version: "3.7"

services:

  jupyter:
    image: threadindata/gluoncv:0.0.1
    ports:
      - 8888:8888
    volumes:
      - ./gluoncv/py_examples/:/home/gluoncv/py_examples/
      - /dev/video0:/dev/video0
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=unix$DISPLAY
    devices:
      - /dev/video0:/dev/video0
    privileged: true

